# Generated by Django 2.2 on 2019-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190406_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='vote',
        ),
        migrations.AddField(
            model_name='likepost',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
